import './globals.css';
import Image from 'next/image';
import Link from 'next/link';
import type { ReactNode } from 'react';

type Props = {
  children: ReactNode;
};

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            <nav>
              <Link href="/">
                <Image
                  src="/images/Printforge_logo.svg"
                  alt="Logo"
                  width={100}
                  height={100}
                />
              </Link>
              <Link href="/register">Register</Link>
              <Link href="/login">Login</Link>
            </nav>
          </div>
        </header>
        <main>{children}</main>
        <footer>PrintForge GmbH ®</footer>
      </body>
    </html>
  );
}
